### ISSUE TITLE
学长学长 为什么访问不了了

### ISSUE THREAD

**Issue by haozi23333** [hide-on-brush/React-Blog#4]
➜ curl -I http://lexblog.cn/ 
curl: (7) Failed to connect to lexblog.cn port 80: Connection refused

网络: 深圳电信
curl : curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0

**Comment by yangger6** [comment]
![image](https://user-images.githubusercontent.com/23329645/53321333-14f0d480-3913-11e9-8a0b-32c84156b149.png)
学长学长我怎么访问不了了啊

**Comment by returnGirlFriendToNull** [comment]
学长，你服务器进黑洞辽

**Comment by haozi23333** [comment]
![](https://i.loli.net/2019/02/25/5c739b70ddb4c.jpg)

**Comment by yangger6** [comment]
![image](https://user-images.githubusercontent.com/23329645/53321490-9e080b80-3913-11e9-96d3-167c99b7d678.png)
学长速速修复

**Comment by zhu-zhu** [comment]
忍不住了嗷

**Comment by haozi23333** [comment]
@hide-on-brush 学弟看好你

**Comment by hide-on-brush** [comment]
别搞我啊大哥们😁

**Comment by hide-on-brush** [comment]
> @皮上刷学弟看好你

别吧昊哥我怕了

**Comment by hide-on-brush** [comment]
> ![图片](https://user-images.githubusercontent.com/23329645/53321490-9e080b80-3913-11e9-96d3-167c99b7d678.png)
> 学长速速修复

你修复🔨

**Comment by hide-on-brush** [comment]
> 忍不住了嗷

？

**Comment by hide-on-brush** [comment]
> 学长，你服务器进黑洞辽

别让我进黑洞鸭
